version: "3"

services:
  app:
    build: ./
    privileged: true
    volumes:
      - ./config:/root/.config
      - ./local:/root/.local
      - ./work:/work
    ports:
      - "8080:8080"
    restart: unless-stopped
